jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/springboot_test?serverTimezone=UTC
  username: root
  password: song

#
spring:
  profiles:
    active: abc,def
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scafflod?serverTimezone=UTC
    username: root
    password: song
  redis:
    host: 192.168.56.124
    port: 6379

#tomcat端口
server:
  port: 80
#日志记录级别
logging:
 # level:
  #  com.itheima: debug
  #  org.springframework: info
mybatis:
  # 实体类别名包路径
  type-aliases-package: com.song.scafflod.pojo
  # 映射文件路径
  # mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl